language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "node"
install: "npm install && npm run release"
after_success: "npm install -g coveralls istanbul mocha && cat ./coverage/lcov.info | coveralls"
